name: Test Prompt Generator Test

on:
  workflow_dispatch:
  schedule:
    - cron: 30 8 * * 1  # run Monday's at 8:30
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install package and dependencies
      run: |
        pip install .
        pip install -r tests/requirements.txt
        pip freeze
    - name: Run test
      run: |
        python -m pytest tests
